name: Package and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This line grants permission to create releases
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         run: npm install

#       - name: Run npm pack
#         run: npm pack

#       - name: Extract version from package.json
#         id: package_version
#         run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"

#       - name: Install GitHub CLI
#         run: sudo apt-get install gh

#       - name: Determine unique tag
#         id: unique_tag
#         run: |
#           VERSION=$(node -p "require('./package.json').version")
#           TAG=$VERSION
#           COUNTER=1
#           while gh release view $TAG &> /dev/null; do
#             TAG="${VERSION}.${COUNTER}"
#             ((COUNTER=COUNTER+1))
#           done
#           echo "::set-output name=TAG::$TAG"

#       - name: Create GitHub Release
#         run: |
#           console.log("Creating release ${{ steps.unique_tag.outputs.TAG }}")
#           console.log({secrets.GITHUB_TOKEN})
#           export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
#           gh release create ${{ steps.unique_tag.outputs.TAG }} --title "Release ${{ steps.unique_tag.outputs.TAG }}" --notes "Automated release based on version ${{ steps.package_version.outputs.VERSION }}."
#         shell: /usr/bin/bash -e {0}

#       - name: Cleanup
#         run: rm *.tgz

name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This line grants permission to create releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm pack
        run: npm pack
        id: npm_pack

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Extract version from package.json
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PACKAGE_FILE=$(ls *.tgz)
          gh release create ${{ env.VERSION }} --title "Release ${{ env.VERSION }}" --notes "Automated release based on version ${{ env.VERSION }}" --draft $PACKAGE_FILE

      - name: Cleanup
        run: rm *.tgz